# Generated by Django 4.2.3 on 2023-07-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amortization",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amortization"
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Principal"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Interest"
                    ),
                ),
                (
                    "principal_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Principal Balance",
                    ),
                ),
                (
                    "interest_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Interest Balance"
                    ),
                ),
                (
                    "surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Surcharge",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loan.microloan",
                        verbose_name="Loan",
                    ),
                ),
            ],
        ),
    ]
