# Generated by Django 4.2.3 on 2023-07-22 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="due_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Due Date"
            ),
        ),
    ]
