# Generated by Django 4.2.3 on 2023-07-22 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "interest_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("montly", "Monthly")],
                        max_length=255,
                        verbose_name="Interest Type",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Interest Rate"
                    ),
                ),
                (
                    "surcharge_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Surcharge Rate"
                    ),
                ),
                (
                    "term_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("montly", "Monthly")],
                        max_length=255,
                        verbose_name="Term Type",
                    ),
                ),
                ("terms", models.IntegerField(verbose_name="Terms")),
            ],
        ),
        migrations.CreateModel(
            name="MicroLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "transaction_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Transaction Date"
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Loan Amount"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirm", "Confirmed"),
                            ("done", "Done"),
                            ("cancel", "Cancelled"),
                        ],
                        default="draft",
                        max_length=255,
                        verbose_name="State",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="member.member",
                        verbose_name="Member",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="loan.loanproduct",
                        verbose_name="Loan Product",
                    ),
                ),
            ],
        ),
    ]
