# Generated by Django 4.2.3 on 2023-07-22 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=255, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=255, verbose_name="Lastname")),
                (
                    "middlename",
                    models.CharField(max_length=255, verbose_name="Middlename"),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
        ),
    ]
